var title;
var material = ["glass", 
            "steel", 
            "iron", 
            "copper", 
            "aluminum", 
            "paper", 
            "jute", 
            "bamboo", 
            "jade", 
            "cotton", 
            "teak",
            "felt",
            "cork",
            "concrete",
            "stone",
            "tile",
            "terracotta",
            "adobe",
            "brick",
            "canvas",
            ];
var place = ["apartment",
            "house",
            "treehouse",
            "loft",
            "bedroom",
            "room",
            "office",
            "chair",
            "table",
            "lamp",
            "bunker",
            "courtyard",
            "garden",
            "veranda",
            "temple",
            "church",
            "convent",
            "factory",
            "park",
            "cellar",
            "storehouse",
            "shelter",
            "garage",
            "workshop",
            "tent",
            "bridge",
            ];
var person = ["a diver",
            "a prawnfisher",
            "a luthier",
            "a weaver",
            "a musician",
            "a dancer",
            "a singer",
            "a metalworker",
            "a boxer",
            "a farmer",
            "a chef",
            "a racer",
            "a choreographer",
            "a neighbor",
            "a birdwatcher",
            "a baker",
            "an editor",
            "a climber",
            "a newcomer",
            "a troupe",
            "a collector",
            "an apologist",
            "an optimist",
            "a flyer",
            "a caretaker",
            "an archivist",
            "an astronomer",
            "a cartographer"];

var personChoice = person[Math.floor(Math.random()*person.length)];
var placeChoice = place[Math.floor(Math.random()*place.length)];
var materialChoice = material[Math.floor(Math.random()*material.length)];

title = materialChoice + " " + placeChoice + " for " + personChoice;

document.getElementById("theBuilding").innerHTML = title;
// document.getElementById("theBuilding").style.color = "gray";

// document.body.style.backgroundColor = "black";
